"""Initial schema: 20+ tables for student management system

Revision ID: c4371dcc7166
Revises: 
Create Date: 2026-06-11 18:26:47.930384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4371dcc7166'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_record', 'approver_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20),
               nullable=False,
               comment='审批人工号')
    op.alter_column('approval_record', 'result',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20),
               nullable=False,
               comment='审批结果：通过/驳回')
    op.alter_column('approval_record', 'comment',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='审批意见',
               existing_nullable=True)
    op.drop_index(op.f('uk_leave_level'), table_name='approval_record')
    op.alter_column('class', 'id',
               existing_type=mysql.INTEGER(),
               comment='班级ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('class', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='班级全称，如：2024级计算机科学1班',
               existing_comment='如：2024级计算机科学1班',
               existing_nullable=False)
    op.alter_column('class', 'major',
               existing_type=mysql.VARCHAR(length=100),
               comment='专业名称',
               existing_nullable=True)
    op.alter_column('class', 'grade',
               existing_type=mysql.INTEGER(),
               comment='入学年份，如2024',
               existing_comment='入学年份',
               existing_nullable=True)
    op.alter_column('class', 'advisor_id',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               comment='辅导员工号，外键关联teacher.id',
               existing_nullable=True)
    op.alter_column('classroom', 'id',
               existing_type=mysql.INTEGER(),
               comment='教室ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('classroom', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment='教室名称，如D201/实验楼A301',
               existing_comment='如D201',
               existing_nullable=False)
    op.alter_column('classroom', 'building',
               existing_type=mysql.VARCHAR(length=50),
               comment='教学楼名称',
               existing_comment='教学楼',
               existing_nullable=True)
    op.alter_column('classroom', 'has_projector',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否有投影仪',
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('uk_room_time'), table_name='classroom_reservation')
    op.alter_column('course_capacity', 'schedule_id',
               existing_type=mysql.INTEGER(),
               comment='关联课表ID',
               existing_nullable=False)
    op.alter_column('course_capacity', 'enrolled',
               existing_type=mysql.INTEGER(),
               comment='已选人数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_capacity', 'capacity',
               existing_type=mysql.INTEGER(),
               comment='课程容量上限',
               existing_nullable=False)
    op.alter_column('course_selection', 'id',
               existing_type=mysql.INTEGER(),
               comment='记录ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('course_selection', 'student_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='学号，对应 student.id',
               existing_comment='学号',
               existing_nullable=False)
    op.alter_column('course_selection', 'schedule_id',
               existing_type=mysql.INTEGER(),
               comment='课表ID',
               existing_nullable=False)
    op.alter_column('course_selection', 'select_time',
               existing_type=mysql.DATETIME(),
               comment='选课时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_selection', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               comment='1=已选(有效), 0=已退(历史记录)',
               existing_comment='1=已选,0=已退',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('course_selection', 'cancel_time',
               existing_type=mysql.DATETIME(),
               comment='退课时间',
               existing_nullable=True)
    op.alter_column('exam', 'id',
               existing_type=mysql.INTEGER(),
               comment='考试ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('exam', 'semester',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='学期，如2024-2025-1',
               existing_nullable=False)
    op.alter_column('exam', 'subject_id',
               existing_type=mysql.INTEGER(),
               comment='科目ID',
               existing_nullable=False)
    op.alter_column('exam', 'schedule_id',
               existing_type=mysql.INTEGER(),
               comment='课表ID',
               existing_nullable=False)
    op.alter_column('exam', 'exam_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='统一考试/随堂考试',
               existing_nullable=False,
               existing_server_default=sa.text("'统一考试'"))
    op.alter_column('exam', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               comment='考试时长(分钟)',
               existing_nullable=False,
               existing_server_default=sa.text("'120'"))
    op.alter_column('exam', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='待排考/已排考/已发布/已结束',
               existing_nullable=False,
               existing_server_default=sa.text("'待排考'"))
    op.alter_column('exam', 'student_count',
               existing_type=mysql.INTEGER(),
               comment='参考学生数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_foreign_key(None, 'exam', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'exam', 'schedule', ['schedule_id'], ['id'])
    op.alter_column('exam_arrangement', 'id',
               existing_type=mysql.INTEGER(),
               comment='安排ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('exam_arrangement', 'exam_id',
               existing_type=mysql.INTEGER(),
               comment='考试ID',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'classroom_id',
               existing_type=mysql.INTEGER(),
               comment='教室ID',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'date',
               existing_type=sa.DATE(),
               comment='考试日期',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'start_time',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='开始时间，如08:00',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'end_time',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='结束时间',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'invigilator_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='监考人工号',
               existing_nullable=True)
    op.drop_index(op.f('uk_exam_room_time'), table_name='exam_arrangement')
    op.create_index('uk_classroom_time', 'exam_arrangement', ['classroom_id', 'date', 'start_time'], unique=True)
    op.create_foreign_key(None, 'exam_arrangement', 'classroom', ['classroom_id'], ['id'])
    op.create_foreign_key(None, 'exam_arrangement', 'exam', ['exam_id'], ['id'])
    op.alter_column('exam_student', 'exam_id',
               existing_type=mysql.INTEGER(),
               comment='考试ID',
               existing_nullable=False)
    op.alter_column('exam_student', 'student_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='学号',
               existing_nullable=False)
    op.alter_column('exam_student', 'seat_no',
               existing_type=mysql.INTEGER(),
               comment='座位号',
               existing_nullable=True)
    op.create_foreign_key(None, 'exam_student', 'exam', ['exam_id'], ['id'])
    op.create_foreign_key(None, 'exam_student', 'student', ['student_id'], ['id'])
    op.alter_column('leave_application', 'student_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20),
               nullable=False,
               comment='学号')
    op.alter_column('leave_application', 'reason',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False,
               comment='请假原因')
    op.alter_column('leave_application', 'status',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20),
               nullable=False,
               comment='状态：审批中(辅导员)/审批中(学院)/已通过/已驳回/已撤销')
    op.alter_column('notification', 'title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200),
               nullable=False,
               comment='通知标题')
    op.alter_column('notification', 'content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False,
               comment='通知正文')
    op.alter_column('notification_user', 'is_read',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               comment='是否已读',
               existing_comment='是否已读 0-未读 1-已读',
               existing_nullable=False)
    op.create_foreign_key(None, 'notification_user', 'notification', ['notification_id'], ['id'])
    op.alter_column('repair', 'id',
               existing_type=mysql.INTEGER(),
               comment='报修ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('repair', 'user_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='报修人学号或工号',
               existing_comment='学号或工号',
               existing_nullable=False)
    op.alter_column('repair', 'role',
               existing_type=mysql.ENUM('student', 'teacher', 'staff'),
               type_=sa.String(length=10),
               comment='报修人角色：student/teacher/staff',
               existing_comment='报修人角色',
               existing_nullable=False)
    op.alter_column('repair', 'location',
               existing_type=mysql.VARCHAR(length=200),
               comment='报修地点',
               existing_comment='报修地点，自由填写',
               existing_nullable=False)
    op.alter_column('repair', 'type',
               existing_type=mysql.ENUM('水电设备', '电子产品', '家具类', '教学用具'),
               type_=sa.String(length=50),
               comment='报修类型：水电设备/电子产品/家具类/教学用具',
               existing_nullable=False)
    op.alter_column('repair', 'description',
               existing_type=mysql.TEXT(),
               comment='问题详细描述',
               existing_comment='故障描述',
               existing_nullable=False)
    op.alter_column('repair', 'status',
               existing_type=mysql.ENUM('提交', '已接单', '处理中', '已完成', '已确认', '已取消'),
               type_=sa.String(length=50),
               comment='当前状态',
               existing_nullable=False,
               existing_server_default=sa.text("'提交'"))
    op.alter_column('repair', 'submit_time',
               existing_type=mysql.DATETIME(),
               comment='提交时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('repair', 'accept_time',
               existing_type=mysql.DATETIME(),
               comment='接单时间',
               existing_nullable=True)
    op.alter_column('repair', 'complete_time',
               existing_type=mysql.DATETIME(),
               comment='完成时间',
               existing_nullable=True)
    op.alter_column('repair', 'confirm_time',
               existing_type=mysql.DATETIME(),
               comment='确认时间',
               existing_nullable=True)
    op.alter_column('repair', 'cancel_time',
               existing_type=mysql.DATETIME(),
               comment='取消时间',
               existing_nullable=True)
    op.alter_column('schedule', 'id',
               existing_type=mysql.INTEGER(),
               comment='课表ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('schedule', 'teacher_id',
               existing_type=mysql.INTEGER(),
               comment='授课教师工号',
               existing_nullable=False)
    op.alter_column('schedule', 'subject_id',
               existing_type=mysql.INTEGER(),
               comment='科目ID',
               existing_nullable=False)
    op.alter_column('schedule', 'class_id',
               existing_type=mysql.INTEGER(),
               comment='授课班级ID',
               existing_nullable=False)
    op.alter_column('schedule', 'classroom_id',
               existing_type=mysql.INTEGER(),
               comment='教室ID',
               existing_nullable=False)
    op.alter_column('schedule', 'weeks',
               existing_type=mysql.VARCHAR(length=20),
               comment='上课周次，如1-18或1-18(单)',
               existing_comment='如1-18或1-18(单)',
               existing_nullable=False)
    op.alter_column('schedule', 'day_of_week',
               existing_type=mysql.INTEGER(),
               comment='星期几，1=周一，7=周日',
               existing_comment='1=周一,7=周日',
               existing_nullable=False)
    op.alter_column('schedule', 'period',
               existing_type=mysql.VARCHAR(length=10),
               comment='节次，如1-2表示第1-2节',
               existing_comment='如1-2表示第1-2节',
               existing_nullable=False)
    op.alter_column('schedule', 'semester',
               existing_type=mysql.VARCHAR(length=20),
               comment='学期，如2024-2025-1',
               existing_comment='如2024-2025-1',
               existing_nullable=False)
    op.alter_column('score', 'id',
               existing_type=mysql.INTEGER(),
               comment='成绩ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('score', 'student_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='学号',
               existing_nullable=False)
    op.alter_column('score', 'schedule_id',
               existing_type=mysql.INTEGER(),
               comment='课表ID',
               existing_nullable=False)
    op.alter_column('score', 'score_type',
               existing_type=mysql.ENUM('平时', '期末', '总评'),
               type_=sa.String(length=20),
               comment='成绩类型：平时/期末/总评',
               existing_nullable=False,
               existing_server_default=sa.text("'总评'"))
    op.alter_column('score', 'attempt',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               comment='考试次数：1=首次, 2=补考',
               existing_comment='1=首次,2=补考',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('score', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('staff', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment='员工姓名',
               existing_nullable=False)
    op.alter_column('staff', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('staff', 'department',
               existing_type=mysql.VARCHAR(length=100),
               comment='所属部门',
               existing_nullable=True)
    op.alter_column('staff', 'job_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='工种：维修/清洁/餐饮等',
               existing_comment='维修/清洁/餐饮等',
               existing_nullable=True)
    op.alter_column('student', 'id',
               existing_type=mysql.VARCHAR(length=20),
               comment='学号作为主键，如S2024001',
               existing_comment='学号作为主键',
               existing_nullable=False)
    op.alter_column('student', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment='学生姓名',
               existing_nullable=False)
    op.alter_column('student', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('student', 'id_card',
               existing_type=mysql.VARCHAR(length=18),
               comment='身份证号，18位',
               existing_nullable=True)
    op.alter_column('student', 'class_id',
               existing_type=mysql.INTEGER(),
               comment='所属班级ID',
               existing_nullable=True)
    op.alter_column('subject', 'id',
               existing_type=mysql.INTEGER(),
               comment='科目ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subject', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='科目名称',
               existing_nullable=False)
    op.alter_column('subject', 'credit',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               comment='学分',
               existing_nullable=False)
    op.alter_column('subject', 'type',
               existing_type=mysql.ENUM('compulsory', 'limited', 'elective'),
               comment='必修(compulsory)/限选(limited)/选修(elective)',
               existing_comment='必修/限选/选修',
               existing_nullable=False,
               existing_server_default=sa.text("'compulsory'"))
    op.alter_column('system_config', 'config_key',
               existing_type=mysql.VARCHAR(length=50),
               comment='配置键',
               existing_nullable=False)
    op.alter_column('system_config', 'config_value',
               existing_type=mysql.VARCHAR(length=255),
               comment='配置值',
               existing_nullable=False)
    op.alter_column('system_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='最后更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('teacher', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment='教师姓名',
               existing_nullable=False)
    op.alter_column('teacher', 'job_number',
               existing_type=mysql.VARCHAR(length=20),
               comment='工号，唯一索引',
               existing_nullable=False)
    op.alter_column('teacher', 'department',
               existing_type=mysql.VARCHAR(length=100),
               comment='所属院系',
               existing_nullable=True)
    op.alter_column('teacher', 'title',
               existing_type=mysql.VARCHAR(length=50),
               comment='职称，如教授/副教授/讲师',
               existing_nullable=True)
    op.alter_column('teacher', 'is_college_admin',
               existing_type=mysql.TINYINT(),
               comment='是否为学院管理员',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_credential', 'id',
               existing_type=mysql.INTEGER(),
               comment='用户ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_credential', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名=学号或工号',
               existing_comment='学号或工号',
               existing_nullable=False)
    op.alter_column('user_credential', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='bcrypt加密后的密码哈希',
               existing_nullable=False)
    op.alter_column('user_credential', 'role',
               existing_type=mysql.ENUM('student', 'teacher', 'staff', 'admin'),
               comment='角色：student/teacher/staff/admin',
               existing_nullable=False)
    op.alter_column('user_credential', 'role_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='对应角色表的主键ID',
               existing_comment='对应角色表的ID',
               existing_nullable=False)
    op.alter_column('user_credential', 'must_change_password',
               existing_type=mysql.TINYINT(display_width=1),
               comment='首次登录是否必须修改密码',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_credential', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='账户创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_credential', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='账户创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_credential', 'must_change_password',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='首次登录是否必须修改密码',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_credential', 'role_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='对应角色表的ID',
               existing_comment='对应角色表的主键ID',
               existing_nullable=False)
    op.alter_column('user_credential', 'role',
               existing_type=mysql.ENUM('student', 'teacher', 'staff', 'admin'),
               comment=None,
               existing_comment='角色：student/teacher/staff/admin',
               existing_nullable=False)
    op.alter_column('user_credential', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt加密后的密码哈希',
               existing_nullable=False)
    op.alter_column('user_credential', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='学号或工号',
               existing_comment='用户名=学号或工号',
               existing_nullable=False)
    op.alter_column('user_credential', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('teacher', 'is_college_admin',
               existing_type=mysql.TINYINT(),
               comment=None,
               existing_comment='是否为学院管理员',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('teacher', 'title',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='职称，如教授/副教授/讲师',
               existing_nullable=True)
    op.alter_column('teacher', 'department',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='所属院系',
               existing_nullable=True)
    op.alter_column('teacher', 'job_number',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='工号，唯一索引',
               existing_nullable=False)
    op.alter_column('teacher', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='教师姓名',
               existing_nullable=False)
    op.alter_column('system_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='最后更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('system_config', 'config_value',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='配置值',
               existing_nullable=False)
    op.alter_column('system_config', 'config_key',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='配置键',
               existing_nullable=False)
    op.alter_column('subject', 'type',
               existing_type=mysql.ENUM('compulsory', 'limited', 'elective'),
               comment='必修/限选/选修',
               existing_comment='必修(compulsory)/限选(limited)/选修(elective)',
               existing_nullable=False,
               existing_server_default=sa.text("'compulsory'"))
    op.alter_column('subject', 'credit',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               comment=None,
               existing_comment='学分',
               existing_nullable=False)
    op.alter_column('subject', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='科目名称',
               existing_nullable=False)
    op.alter_column('subject', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='科目ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('student', 'class_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属班级ID',
               existing_nullable=True)
    op.alter_column('student', 'id_card',
               existing_type=mysql.VARCHAR(length=18),
               comment=None,
               existing_comment='身份证号，18位',
               existing_nullable=True)
    op.alter_column('student', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('student', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='学生姓名',
               existing_nullable=False)
    op.alter_column('student', 'id',
               existing_type=mysql.VARCHAR(length=20),
               comment='学号作为主键',
               existing_comment='学号作为主键，如S2024001',
               existing_nullable=False)
    op.alter_column('staff', 'job_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='维修/清洁/餐饮等',
               existing_comment='工种：维修/清洁/餐饮等',
               existing_nullable=True)
    op.alter_column('staff', 'department',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='所属部门',
               existing_nullable=True)
    op.alter_column('staff', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('staff', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='员工姓名',
               existing_nullable=False)
    op.alter_column('score', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('score', 'attempt',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               comment='1=首次,2=补考',
               existing_comment='考试次数：1=首次, 2=补考',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('score', 'score_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('平时', '期末', '总评'),
               comment=None,
               existing_comment='成绩类型：平时/期末/总评',
               existing_nullable=False,
               existing_server_default=sa.text("'总评'"))
    op.alter_column('score', 'schedule_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='课表ID',
               existing_nullable=False)
    op.alter_column('score', 'student_id',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='学号',
               existing_nullable=False)
    op.alter_column('score', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='成绩ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('schedule', 'semester',
               existing_type=mysql.VARCHAR(length=20),
               comment='如2024-2025-1',
               existing_comment='学期，如2024-2025-1',
               existing_nullable=False)
    op.alter_column('schedule', 'period',
               existing_type=mysql.VARCHAR(length=10),
               comment='如1-2表示第1-2节',
               existing_comment='节次，如1-2表示第1-2节',
               existing_nullable=False)
    op.alter_column('schedule', 'day_of_week',
               existing_type=mysql.INTEGER(),
               comment='1=周一,7=周日',
               existing_comment='星期几，1=周一，7=周日',
               existing_nullable=False)
    op.alter_column('schedule', 'weeks',
               existing_type=mysql.VARCHAR(length=20),
               comment='如1-18或1-18(单)',
               existing_comment='上课周次，如1-18或1-18(单)',
               existing_nullable=False)
    op.alter_column('schedule', 'classroom_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='教室ID',
               existing_nullable=False)
    op.alter_column('schedule', 'class_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='授课班级ID',
               existing_nullable=False)
    op.alter_column('schedule', 'subject_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='科目ID',
               existing_nullable=False)
    op.alter_column('schedule', 'teacher_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='授课教师工号',
               existing_nullable=False)
    op.alter_column('schedule', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='课表ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('repair', 'cancel_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='取消时间',
               existing_nullable=True)
    op.alter_column('repair', 'confirm_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='确认时间',
               existing_nullable=True)
    op.alter_column('repair', 'complete_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('repair', 'accept_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='接单时间',
               existing_nullable=True)
    op.alter_column('repair', 'submit_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='提交时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('repair', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('提交', '已接单', '处理中', '已完成', '已确认', '已取消'),
               comment=None,
               existing_comment='当前状态',
               existing_nullable=False,
               existing_server_default=sa.text("'提交'"))
    op.alter_column('repair', 'description',
               existing_type=mysql.TEXT(),
               comment='故障描述',
               existing_comment='问题详细描述',
               existing_nullable=False)
    op.alter_column('repair', 'type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('水电设备', '电子产品', '家具类', '教学用具'),
               comment=None,
               existing_comment='报修类型：水电设备/电子产品/家具类/教学用具',
               existing_nullable=False)
    op.alter_column('repair', 'location',
               existing_type=mysql.VARCHAR(length=200),
               comment='报修地点，自由填写',
               existing_comment='报修地点',
               existing_nullable=False)
    op.alter_column('repair', 'role',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('student', 'teacher', 'staff'),
               comment='报修人角色',
               existing_comment='报修人角色：student/teacher/staff',
               existing_nullable=False)
    op.alter_column('repair', 'user_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='学号或工号',
               existing_comment='报修人学号或工号',
               existing_nullable=False)
    op.alter_column('repair', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='报修ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'notification_user', type_='foreignkey')
    op.alter_column('notification_user', 'is_read',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               comment='是否已读 0-未读 1-已读',
               existing_comment='是否已读',
               existing_nullable=False)
    op.alter_column('notification', 'content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=True,
               comment=None,
               existing_comment='通知正文')
    op.alter_column('notification', 'title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200),
               nullable=True,
               comment=None,
               existing_comment='通知标题')
    op.alter_column('leave_application', 'status',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20),
               nullable=True,
               comment=None,
               existing_comment='状态：审批中(辅导员)/审批中(学院)/已通过/已驳回/已撤销')
    op.alter_column('leave_application', 'reason',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=True,
               comment=None,
               existing_comment='请假原因')
    op.alter_column('leave_application', 'student_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20),
               nullable=True,
               comment=None,
               existing_comment='学号')
    op.drop_constraint(None, 'exam_student', type_='foreignkey')
    op.drop_constraint(None, 'exam_student', type_='foreignkey')
    op.alter_column('exam_student', 'seat_no',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='座位号',
               existing_nullable=True)
    op.alter_column('exam_student', 'student_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='学号',
               existing_nullable=False)
    op.alter_column('exam_student', 'exam_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='考试ID',
               existing_nullable=False)
    op.drop_constraint(None, 'exam_arrangement', type_='foreignkey')
    op.drop_constraint(None, 'exam_arrangement', type_='foreignkey')
    op.drop_index('uk_classroom_time', table_name='exam_arrangement')
    op.create_index(op.f('uk_exam_room_time'), 'exam_arrangement', ['classroom_id', 'date', 'start_time'], unique=True)
    op.alter_column('exam_arrangement', 'invigilator_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='监考人工号',
               existing_nullable=True)
    op.alter_column('exam_arrangement', 'end_time',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'start_time',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='开始时间，如08:00',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='考试日期',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'classroom_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='教室ID',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'exam_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='考试ID',
               existing_nullable=False)
    op.alter_column('exam_arrangement', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='安排ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.alter_column('exam', 'student_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='参考学生数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('exam', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='待排考/已排考/已发布/已结束',
               existing_nullable=False,
               existing_server_default=sa.text("'待排考'"))
    op.alter_column('exam', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='考试时长(分钟)',
               existing_nullable=False,
               existing_server_default=sa.text("'120'"))
    op.alter_column('exam', 'exam_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='统一考试/随堂考试',
               existing_nullable=False,
               existing_server_default=sa.text("'统一考试'"))
    op.alter_column('exam', 'schedule_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='课表ID',
               existing_nullable=False)
    op.alter_column('exam', 'subject_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='科目ID',
               existing_nullable=False)
    op.alter_column('exam', 'semester',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='学期，如2024-2025-1',
               existing_nullable=False)
    op.alter_column('exam', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='考试ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('course_selection', 'cancel_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='退课时间',
               existing_nullable=True)
    op.alter_column('course_selection', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               comment='1=已选,0=已退',
               existing_comment='1=已选(有效), 0=已退(历史记录)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('course_selection', 'select_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='选课时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_selection', 'schedule_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='课表ID',
               existing_nullable=False)
    op.alter_column('course_selection', 'student_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='学号',
               existing_comment='学号，对应 student.id',
               existing_nullable=False)
    op.alter_column('course_selection', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='记录ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('course_capacity', 'capacity',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='课程容量上限',
               existing_nullable=False)
    op.alter_column('course_capacity', 'enrolled',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='已选人数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_capacity', 'schedule_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联课表ID',
               existing_nullable=False)
    op.create_index(op.f('uk_room_time'), 'classroom_reservation', ['classroom_id', 'week', 'day_of_week', 'period'], unique=True)
    op.alter_column('classroom', 'has_projector',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment=None,
               existing_comment='是否有投影仪',
               existing_server_default=sa.text("'0'"))
    op.alter_column('classroom', 'building',
               existing_type=mysql.VARCHAR(length=50),
               comment='教学楼',
               existing_comment='教学楼名称',
               existing_nullable=True)
    op.alter_column('classroom', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment='如D201',
               existing_comment='教室名称，如D201/实验楼A301',
               existing_nullable=False)
    op.alter_column('classroom', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='教室ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('class', 'advisor_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='辅导员工号，外键关联teacher.id',
               existing_nullable=True)
    op.alter_column('class', 'grade',
               existing_type=mysql.INTEGER(),
               comment='入学年份',
               existing_comment='入学年份，如2024',
               existing_nullable=True)
    op.alter_column('class', 'major',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='专业名称',
               existing_nullable=True)
    op.alter_column('class', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='如：2024级计算机科学1班',
               existing_comment='班级全称，如：2024级计算机科学1班',
               existing_nullable=False)
    op.alter_column('class', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='班级ID，自增',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('uk_leave_level'), 'approval_record', ['leave_id', 'level'], unique=True)
    op.alter_column('approval_record', 'comment',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment=None,
               existing_comment='审批意见',
               existing_nullable=True)
    op.alter_column('approval_record', 'result',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20),
               nullable=True,
               comment=None,
               existing_comment='审批结果：通过/驳回')
    op.alter_column('approval_record', 'approver_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20),
               nullable=True,
               comment=None,
               existing_comment='审批人工号')
    # ### end Alembic commands ###
